from pathlib import Path

from exasol.toolbox.config import BaseConfig
from pydantic import computed_field

ROOT_DIR = Path(__file__).parent


class Config(BaseConfig):
    @computed_field  # type: ignore[misc]
    @property
    def version_filepath(self) -> Path:
        """
        Path to the ``version.py`` file included in the project. This is an
        autogenerated file which contains the version of the code. It is maintained by
        the nox sessions ``version:check`` and ``release:prepare``.

         In transformers-extension, this needs to be overridden due to a custom directory
        setup & custom `version.py` location. This will be addressed in:
            https://github.com/exasol/advanced-analytics-framework/issues/340
        """
        return self.root_path / "version.py"


PROJECT_CONFIG = Config(
    root_path=ROOT_DIR,
    project_name="analytics",
    python_versions=("3.10",),
    add_to_excluded_python_paths=(".conda_env", ".luarocks"),
)
