@startuml
'https://plantuml.com/sequence-diagram

!include ../legend.puml

box Peer1
    participant "DiscoveryStrategy" as DiscoveryStrategy1
    participant "PeerCommunicator\n(Formation Leader)" as PeerCommunicator1
end box

box Peer2
    participant "DiscoveryStrategy" as DiscoveryStrategy2
    participant "PeerCommunicator" as PeerCommunicator2
end box

box Peer3
    participant "DiscoveryStrategy" as DiscoveryStrategy3
    participant "PeerCommunicator" as PeerCommunicator3
end box

box Peer4
    participant "DiscoveryStrategy" as DiscoveryStrategy4
    participant "PeerCommunicator" as PeerCommunicator4
end box
par
    loop all_peers_are_connected
        DiscoveryStrategy1 <- DiscoveryStrategy2: PingMessage
        DiscoveryStrategy1 -> PeerCommunicator1: register_peer(Peer2)
        ref over PeerCommunicator1, PeerCommunicator4: Global Cluster Formation
        DiscoveryStrategy2 -> PeerCommunicator2: are_all_peers_connected()
    end
else
    loop all_peers_are_connected
        DiscoveryStrategy1 <- DiscoveryStrategy3: PingMessage
        DiscoveryStrategy1 -> PeerCommunicator1: register_peer(Peer3)
        ref over PeerCommunicator1, PeerCommunicator4: Global Cluster Formation
        DiscoveryStrategy3 -> PeerCommunicator3: are_all_peers_connected()
    end
else
    loop all_peers_are_connected
        DiscoveryStrategy1 <- DiscoveryStrategy4: PingMessage
        DiscoveryStrategy1 -> PeerCommunicator1: register_peer(Peer4)
        ref over PeerCommunicator1, PeerCommunicator4: Global Cluster Formation
        DiscoveryStrategy4 -> PeerCommunicator4: are_all_peers_connected()
    end
end
@enduml