@startuml
'https://plantuml.com/sequence-diagram

!include base.puml

par
    [-[$method_call]> Peer1Frontend: register_peer()
    Peer1Frontend -[$zmq_inproc]>> Peer1Backend: RegisterPeerMessage
    Peer1Backend -[$zmq_tcp_rd_no_con]x Peer2Backend: SynchronizeConnectionMessage
else
    Peer2Frontend <[$method_call]-] : register_peer()
    Peer2Backend <<[$zmq_inproc]- Peer2Frontend: RegisterPeerMessage
    Peer1Backend x[$zmq_tcp_rd_no_con]- Peer2Backend : SynchronizeConnectionMessage
end

loop until abort timeout
    par
        ...synchronize_timeout...
        Peer1Backend -[$zmq_tcp_rd_no_con]x Peer2Backend: SynchronizeConnectionMessage
    else
        ...synchronize_timeout...
        Peer1Backend x[$zmq_tcp_rd_no_con]- Peer2Backend : SynchronizeConnectionMessage
    end
end

par
    Peer2Backend -[$zmq_inproc]>> Peer2Frontend: TimeoutMessage
else
    Peer1Frontend <<[$zmq_inproc]- Peer1Backend: TimeoutMessage
end

@enduml