name: CD

on:
  push:
    tags:
      - '**'

jobs:

  check-tag-version-job:
    name: Check Release Tag
    uses: ./.github/workflows/check-release-tag.yml
    permissions:
      contents: read

  cd-job:
    name: Continuous Delivery
    uses: ./.github/workflows/build-and-publish.yml
    permissions:
      contents: write
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

# This step is disabled, because the project does not support sphinx yet

#   publish-docs:
#     needs: [ cd-job ]
#     name: Publish Documentation
#     uses: ./.github/workflows/gh-pages.yml
#     permissions:
#       contents: read
#       pages: write
#       id-token: write

