name: Check Code Generation

on:
  workflow_call:

jobs:
  build-matrix:
    name: Build Matrix
    uses: ./.github/workflows/matrix.yml
    with:
      matrix_keys_json: '["minimum_python_version"]'
    permissions:
      contents: read

  check_code_generation:
    name: Lua Amalgate
    runs-on: ubuntu-24.04
    needs:
      - build-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    steps:
      - name: Check out Repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v10
        with:
          python-version: ${{ matrix.minimum_python_version }}
          poetry-version: "2.3.0"

      - name: Install Development Environment
        run: poetry run -- nox -s devenv:install

      - name: Poetry Install
        run: poetry run -- nox -s devenv:run -- poetry install

      - name: Amalgate Lua Scripts
        run: poetry run -- nox -s lua:amalgate

      - name: Check if Re-Generated Files Differ From Commit
        run: git diff --exit-code
