name: Publish Documentation

on:
  workflow_call:
  workflow_dispatch:

jobs:

  build-documentation:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

#      These steps are disabled, because the project does not support sphinx yet

#       - name: Setup Python & Poetry Environment
#         uses: exasol/python-toolbox/.github/actions/python-environment@1.2.0
#
#       - name: Build Documentation
#         run: |
#           poetry run -- nox -s docs:multiversion
#           rm -r .html-documentation/*/.doctrees
#
#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v3
#         with:
#           path: .html-documentation

# This job is disabled, because the project does not support sphinx yet

#   deploy-documentation:
#     needs: [ build-documentation ]
#     permissions:
#       contents: read
#       pages: write
#       id-token: write
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-24.04
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v4
