name: Run integration tests with DB

on: [ push ]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
    runs-on: ubuntu-latest

    steps:

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.0
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: ./.github/actions/prepare_poetry_env

      - name: Install Lua environment
        run: poetry run -- nox -s install_lua_environment

      - name: Poetry install
        run: poetry run -- nox -s run_in_dev_env -- poetry install

      - name: Build language container
        run: poetry run -- nox -s build_language_container

      - name: Start test environment
        run: poetry run -- nox -s start_integration_test_environment

      - name: Run Python integration tests with db
        run: poetry run -- nox -s run_python_integration_tests_with_db
