name: Merge-Gate

on:
  workflow_call:

jobs:

  experiment:
    uses: ./.github/workflows/tests-matrix.yml
    with:
      python-version: "3.10"
    permissions:
      contents: read

  fast-checks:
    name: Fast
    uses: ./.github/workflows/checks.yml
    permissions:
      contents: read

  slow-checks:
    name: Slow
    uses: ./.github/workflows/slow-checks.yml
    permissions:
      contents: read

  # This job ensures inputs have been executed successfully.
  approve-merge:
    name: Allow Merge
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    # If you need additional jobs to be part of the merge gate, add them below
    needs: [ fast-checks, slow-checks ]

    # Each job requires a step, so we added this dummy step.
    steps:
      - name: Approve
        run: |
          echo "Merge Approved"
