name: Slow-Checks

on:
  workflow_call:

jobs:
  build-matrix:
    name: Build Matrix
    uses: ./.github/workflows/matrix.yml
    with:
      matrix_keys_json: '["minimum_python_version"]'
    permissions:
      contents: read

  run-itests-no-db:
    name: iTests (no DB)
    needs:
      - build-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    permissions:
      contents: read
    uses: ./.github/workflows/tests-integration-no-db.yml
    with:
      python-version: ${{ matrix.minimum_python_version }}

  run-itests-with-db:
    name: iTests (with DB)
    needs:
      - build-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    permissions:
      contents: read
    uses: ./.github/workflows/tests-integration-db.yml
    with:
      python-version: ${{ matrix.minimum_python_version }}