name: Run unit tests

on: [ push ]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python & Poetry Environment
        uses: ./.github/actions/prepare_poetry_env

      - name: Install Lua environment
        run: poetry run -- nox -s install_lua_environment

      - name: Poetry install
        run: poetry run -- nox -s run_in_dev_env -- poetry install

      - name: Run Lua unit tests and static code analyzer
        run: poetry run -- nox -s run_in_dev_env -- ./scripts/lua_tests.sh

      - name: Run Python unit tests
        run: poetry run -- nox -s run_python_unit_tests
